spring:
  application:
    name: tenant-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 500
            readTimeout: 2000
            loggerLevel: basic
            micrometer.enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
