spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: identity-auth-route
            uri: ${arenax.gateway.routes.identity-service}
            predicates:
              - Path=/api/v1/auth/**
          - id: identity-users-route
            uri: ${arenax.gateway.routes.identity-service}
            predicates:
              - Path=/api/v1/users/**

management:
  endpoints:
    web:
      exposure:
        include: health

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true

arenax:
  gateway:
    routes:
      identity-service: lb://identity-service
  security:
    jwt:
      issuer: arenax-identity
      audience: arenax-api
      secret: ${ARENAX_JWT_SECRET}
