CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    gender VARCHAR(20) NOT NULL
);

INSERT INTO users (name, email, password, gender)
VALUES ('khang', 'khangdeptrai@gmail.com', '123456', 'MALE');
