CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    token VARCHAR(1000) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE
);

UPDATE users
SET password = '$2a$10$mKSs.yiDAL45yioM99kVIeoXkzblREo6KV7/Buk.7DoIV7i7YWbJa'
WHERE email = 'khangdeptrai@gmail.com'
  AND password = '123456';
