CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    owner_user_id BIGINT REFERENCES users(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL UNIQUE REFERENCES accounts(id),
    plan VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    version INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE users ADD COLUMN full_name VARCHAR(120);
ALTER TABLE users ADD COLUMN display_name VARCHAR(80);
ALTER TABLE users ADD COLUMN phone_number VARCHAR(30);
ALTER TABLE users ADD COLUMN avatar_url VARCHAR(500);
ALTER TABLE users ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE users ADD COLUMN role VARCHAR(30) NOT NULL DEFAULT 'USER';
ALTER TABLE users ADD COLUMN account_id BIGINT REFERENCES accounts(id);
ALTER TABLE users ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN created_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN version INTEGER NOT NULL DEFAULT 0;

UPDATE users
SET full_name = name,
    display_name = name
WHERE full_name IS NULL;

INSERT INTO accounts (name, type, status, owner_user_id, is_active, version)
SELECT COALESCE(NULLIF(display_name, ''), name, email) || '''s Account', 'PERSONAL', 'ACTIVE', id, TRUE, 0
FROM users
WHERE account_id IS NULL;

UPDATE users u
SET account_id = a.id
FROM accounts a
WHERE a.owner_user_id = u.id
  AND u.account_id IS NULL;

INSERT INTO subscriptions (account_id, plan, status, started_at, is_active, version)
SELECT a.id, 'FREE', 'ACTIVE', CURRENT_TIMESTAMP, TRUE, 0
FROM accounts a
LEFT JOIN subscriptions s ON s.account_id = a.id
WHERE s.id IS NULL;
