CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    code_name VARCHAR(120) NOT NULL UNIQUE,
    module VARCHAR(80) NOT NULL,
    action VARCHAR(80) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    code_name VARCHAR(80) NOT NULL UNIQUE,
    description VARCHAR(500),
    system_role BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE user_role_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    account_id BIGINT REFERENCES accounts(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_user_role_assignments_user_account_role UNIQUE (user_id, account_id, role_id)
);

INSERT INTO permissions (name, code_name, module, action, description, is_active, version)
VALUES
    ('Account View', 'ACCOUNT_VIEW', 'ACCOUNT', 'VIEW', 'View account/workspace data', TRUE, 0),
    ('Account Manage', 'ACCOUNT_MANAGE', 'ACCOUNT', 'MANAGE', 'Manage account/workspace settings', TRUE, 0),
    ('User View', 'USER_VIEW', 'USER', 'VIEW', 'View users', TRUE, 0),
    ('User Create', 'USER_CREATE', 'USER', 'CREATE', 'Create users', TRUE, 0),
    ('User Update', 'USER_UPDATE', 'USER', 'UPDATE', 'Update users', TRUE, 0),
    ('User Delete', 'USER_DELETE', 'USER', 'DELETE', 'Delete users', TRUE, 0),
    ('RBAC View', 'RBAC_VIEW', 'RBAC', 'VIEW', 'View roles and permissions', TRUE, 0),
    ('RBAC Manage', 'RBAC_MANAGE', 'RBAC', 'MANAGE', 'Manage roles and permissions', TRUE, 0),
    ('Court View', 'COURT_VIEW', 'COURT', 'VIEW', 'View court modules', TRUE, 0),
    ('Court Manage', 'COURT_MANAGE', 'COURT', 'MANAGE', 'Manage court modules', TRUE, 0),
    ('Booking View', 'BOOKING_VIEW', 'BOOKING', 'VIEW', 'View booking modules', TRUE, 0),
    ('Booking Manage', 'BOOKING_MANAGE', 'BOOKING', 'MANAGE', 'Manage booking modules', TRUE, 0),
    ('Subscription View', 'SUBSCRIPTION_VIEW', 'SUBSCRIPTION', 'VIEW', 'View subscriptions', TRUE, 0),
    ('Subscription Manage', 'SUBSCRIPTION_MANAGE', 'SUBSCRIPTION', 'MANAGE', 'Manage subscriptions', TRUE, 0),
    ('Report View', 'REPORT_VIEW', 'REPORT', 'VIEW', 'View reports', TRUE, 0),
    ('System Config Manage', 'SYSTEM_CONFIG_MANAGE', 'SYSTEM_CONFIG', 'MANAGE', 'Manage system configuration', TRUE, 0)
ON CONFLICT (code_name) DO NOTHING;

INSERT INTO roles (name, code_name, description, system_role, is_active, version)
VALUES
    ('Admin', 'ADMIN', 'Full platform administrator', TRUE, TRUE, 0),
    ('Manager', 'MANAGER', 'Module manager', FALSE, TRUE, 0),
    ('Staff', 'STAFF', 'Operational staff', FALSE, TRUE, 0),
    ('User', 'USER', 'Default end user', TRUE, TRUE, 0)
ON CONFLICT (code_name) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.code_name = 'ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code_name IN (
    'USER_VIEW',
    'COURT_MANAGE',
    'BOOKING_MANAGE',
    'SUBSCRIPTION_VIEW',
    'REPORT_VIEW'
)
WHERE r.code_name = 'MANAGER'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code_name IN ('COURT_VIEW', 'BOOKING_VIEW')
WHERE r.code_name = 'STAFF'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code_name IN ('ACCOUNT_VIEW')
WHERE r.code_name = 'USER'
ON CONFLICT DO NOTHING;

INSERT INTO user_role_assignments (user_id, account_id, role_id, is_active, version)
SELECT u.id, u.account_id, r.id, TRUE, 0
FROM users u
JOIN roles r ON r.code_name = CASE WHEN u.email = 'khangdeptrai@gmail.com' THEN 'ADMIN' ELSE COALESCE(u.role, 'USER') END
ON CONFLICT DO NOTHING;
