server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://${ARENAX_DB_HOST:localhost}:${ARENAX_DB_PORT:5432}/${ARENAX_SUBSCRIPTION_DB:arenax_subscription}
    username: ${ARENAX_DB_USER:postgres}
    password: ${ARENAX_DB_PASSWORD:postgres}
